name: Install
description: Setup Node.js and PNPM and install dependencies

runs:
  using: "composite"

  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ./.nvmrc
        cache: pnpm

    - name: Setup Turborepo cache
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.job }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ github.job }}
          ${{ runner.os }}-turbo

    - name: Install dependencies
      shell: bash
      run: pnpm install
